# Generated by Django 4.1.2 on 2022-11-29 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ausentismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('tipoId', models.CharField(max_length=10)),
                ('identificacion', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('tipoIncapacidad', models.CharField(choices=[('Enfermedad Comun', 'Enfermedad Común'), ('Licencia Mat-Pat', 'Licencia Maternidad/Paternidad'), ('Accidente Laboral', 'Accidente de Trabajo'), ('Enfermedad Laboral', 'Enfermedad Laboral'), ('Fondo de Pensiones', 'Fondo de Pensiones'), ('Accidente de Transito', 'Accidente de Transito')], max_length=100)),
                ('salario', models.CharField(max_length=80)),
                ('eps', models.CharField(default='', max_length=100)),
                ('afp', models.CharField(default='', max_length=100)),
                ('arl', models.CharField(default='', max_length=100)),
                ('salarioDia', models.CharField(max_length=10)),
                ('fechaInicial', models.DateField(default=django.utils.timezone.now)),
                ('fechaFinal', models.DateField(default=django.utils.timezone.now)),
                ('totalDias', models.IntegerField()),
                ('clasificacion', models.CharField(choices=[('Inicial', 'Inicial'), ('Prorroga', 'Prorroga')], max_length=10)),
                ('totalEmpresa', models.CharField(default='', max_length=20)),
                ('totalArl', models.CharField(default='', max_length=30)),
                ('totalAFP', models.CharField(default='', max_length=30)),
                ('totalEPS', models.CharField(default='', max_length=30)),
                ('totalIncapacidad', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
