# Generated by Django 4.1.2 on 2022-11-23 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='afp',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='arl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='totalAFP',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='totalArl',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='totalEPS',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='totalEmpresa',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='totalIncapacidad',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='clasificacion',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='eps',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='fechaFinal',
            field=models.DateField(default=datetime.datetime(2022, 11, 23, 12, 49, 14, 982016, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='fechaInicial',
            field=models.DateField(auto_now_add=True),
        ),
    ]
