# Generated by Django 4.1.2 on 2022-11-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('tipoId', models.CharField(max_length=10)),
                ('identificacion', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('doc_arl', models.CharField(max_length=100)),
                ('doc_afp', models.CharField(max_length=80)),
                ('doc_eps', models.CharField(max_length=100)),
            ],
        ),
    ]
