from django.db import models
from django.utils import timezone

class ausentismo(models.Model):
    OpcionesTipo=(('Enfermedad Comun','Enfermedad Común'),('Licencia Mat-Pat','Licencia Maternidad/Paternidad'),('Accidente Laboral','Accidente de Trabajo'),('Enfermedad Laboral','Enfermedad Laboral'),('Fondo de Pensiones','Fondo de Pensiones'),('Accidente de Transito','Accidente de Transito'))
    OpcionesClasificacion=(('Inicial','Inicial'),('Prorroga','Prorroga'))
    nombres=models.CharField(max_length=80)
    apellidos=models.CharField(max_length=80)
    tipoId=models.CharField(max_length=10)
    identificacion=models.CharField(max_length=20)
    cargo=models.CharField(max_length=20)
    tipoIncapacidad=models.CharField(max_length=100,choices=OpcionesTipo)
    salario=models.CharField(max_length=80)
    eps=models.CharField(max_length=100,default="")
    afp=models.CharField(max_length=100,default="")
    arl=models.CharField(max_length=100,default="")
    salarioDia=models.CharField(max_length=10)
    fechaInicial=models.DateField(default=timezone.now())
    fechaFinal=models.DateField(default=timezone.now())
    totalDias=models.IntegerField()
    clasificacion=models.CharField(max_length=10,choices=OpcionesClasificacion)
    totalEmpresa=models.CharField(max_length=20,default="")
    totalArl=models.CharField(max_length=30,default="")
    totalAFP=models.CharField(max_length=30,default="")
    totalEPS=models.CharField(max_length=30,default="")
    totalIncapacidad=models.CharField(max_length=30,default="")
