# Generated by Django 4.1.2 on 2022-11-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreusuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=10)),
                ('idEmpleado', models.IntegerField()),
            ],
        ),
    ]
